name: .NET Core Desktop

on:
  pull_request:
    branches:
      - qa-test(dev)
      - main

jobs:

 build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar projeto
        run: dotnet build --no-restore --configuration Release

      - name: Publicar aplicação
        run: dotnet publish --configuration Release --output ./publish

      - name: Upload do artefato (opcional)
        uses: actions/upload-artifact@v4
        with:
          name: app-publish
          path: ./publish
